### PR TITLE
Add 2 more NLP suppression levels, pause filter adaptation when output muted

### PR DESCRIPTION
**Pull request by skywhale**
Exporting my work on AEC so far, so I'm not deep in a silo.

* Add more granular NLP levels
* Pause filter adaptation while the output is muted

### CODE REVIEW

**Review by strohel — COMMENTED** [review]
I went casually through the changes, understood the intent, nothing suspicious came into my mind (but it's been quite some time since I was writing/reviewing C/C++ code).

**Comment by skywhale** [comment]
Thank you @strohel. This will hopefully improve the howling that happens after existing low-power mode, but I still need to look into solving more general howling that happens when the filter adaptation finds a bad local optima. I plan to do a bit more testing tomorrow.

**Comment by skywhale** [comment]
I'm experimenting throttling of FIR filter adaptation based on the relative activity of the far end w.r.t. the near end, which is the purple dots in the plot below. The first 1/4 is where both sides are inactive, the 2nd with far-end active, the 3rd with near-end active, and the last 1/4 with both sides active.

four-modes

**Comment by skywhale** [comment]
Reverted the FIR filter adaptation pause based on far end detection. I will start simple with just the explicit hint for pausing filter adaptation and NLP level additions.

**Comment by skywhale** [comment]
@strohel This is ready for review. It is basically back to where it was when the PR was opened.

**Review by strohel — APPROVED** [review]
Nicely straightforward! Only thing I'd change is the PR title so that it describes more specifically what is done, something like:
`Add 2 more NLP suppression levels, pause filter adaptation when output muted`

**Comment by skywhale** [comment]
Closing the PR; the `aec-fixes` branch will stay, that the `webrtc-audio-processing` crate will depend on. In the future, we will want to migrate back to the trunk of `pulse-webrtc-audio-processing` and merge this PR in, but not for now as it's going to be a lot of work having to validate all the processors that changed.

**Pull request closed without merging**
